http:
  listener:
    host: "0.0.0.0"
    port: "8082"
    
db:
  mysql:
    host: "![rJH1CaRsM99c5aScj86BQQ==]"
    port: "3306"
    user: "![g57EsmuByv0HFJ47YpNvbQ==]"
    password: "![1v+gXEoqC+10lDm2BgDQmA==]"
    database: "zBh5T2rC8k"
smtp:
  host: "smtp.gmail.com"
  port: "587"
  email: "![z1eS/OaKP2IfaamxiMKZBjunaDE/Lcc1]"
  password: "![vfTXNOyaVaW+vackEWXaIg==]"